### ISSUE TITLE
What url should i use for api?

### ISSUE THREAD

**Issue by ivanhuay** [krisboit/protractor-xmlhttprequest-mock#6]
Hi, I'm not sure what url should use from the provider to work correctly

I could not get it to work with 
```
http.get(url).toPromise()
```
i 'm using angular 2

**Comment by krisboit** [comment]
Hi, you should use the url of your webapp. I usualy user `browser.get(url)`.

**Comment by ivanhuay** [comment]
If it was my mistake, the library works well. Thank you very much
